name: Maivin

on:
  push:
    branches: '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for Maivin
    runs-on: ubuntu-latest
    container:
      image: deepview/rust:1.77.2
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Fix Permissions
      run: git config --system --add safe.directory '*'

    - name: Parse Version
      run: echo GIT_VERSION=$(git describe --tags | cut -b2-) >> $GITHUB_ENV

    - name: Update Version
      run: |
        sed -i "s/0.0.0/$GIT_VERSION/g" Cargo.toml

    - name: Build
      run: cargo build --release --target aarch64-unknown-linux-gnu --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\"

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: target/aarch64-unknown-linux-gnu/release/maivin-localtime
